### ISSUE TITLE
和 JavaScript SDK 接口一致

### ISSUE THREAD

**Issue by nicecui** [leancloud/Play-SDK-CSharp#10]
1. AV.Leaderboard.updateStatistics 第二个参数为 Object。

**Comment by onerain88** [comment]
https://leansdk.visualstudio.com/_git/LeanCloud-dotNet-SDK/pullrequest/115?_a=overview
成绩参数修改为 Dictionary<string, object> 类型

**Comment by nicecui** [comment]
已解决
